//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_ISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSection
    {
        public int SID { get; set; }
        public int AID { get; set; }
        public Nullable<bool> speaker { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Section Section { get; set; }
    }
}
